# Generated by Django 3.2.25 on 2024-10-29 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awesome_chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatBot',
            new_name='ChatBotModel',
        ),
    ]
