# Generated by Django 3.2.25 on 2024-10-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awesome_chatbot', '0002_rename_chatbot_chatbotmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotmodel',
            name='bot_response',
            field=models.TextField(blank=True),
        ),
    ]
